name: Build

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [
          # 18, 
          20,
        ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: corepack enable
    - run: yarn --version
    - run: yarn install --immutable
    - run: yarn audit
    - run: yarn lint
